# Generated by Django 3.0.2 on 2020-02-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
