# Generated by Django 3.0.2 on 2020-02-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200207_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
    ]
