# Generated by Django 3.0.2 on 2020-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200210_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.RemoveField(
            model_name='product',
            name='producer',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ManyToManyField(blank=True, to='products.Producer'),
        ),
    ]
